/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'devsci5' at '10/25/16 12:46 AM' with Gradle 3.1
 *
 * @author devsci5, @date 10/25/16 12:46 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
