package htsbox
/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'devsci5' at '10/25/16 12:46 AM' with Gradle 3.1
 *
 * @author devsci5, @date 10/25/16 12:46 AM
 */
import spock.lang.Specification

class AlignmentLibraryTest extends Specification {

    def ""(){

    }

    def "parse aligned methods"() {
        setup:
        AlignmentLibrary lib = new AlignmentLibrary()
        when:
        def result = lib.parseAlignmentsVersion(new File("src/test/resources/SixGenomes.htsbox.out"))
        then:
        assert 1001 == result.entries.size()
    }
}
