/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'devsci5' at '10/25/16 12:46 AM' with Gradle 3.1
 *
 * @author devsci5, @date 10/25/16 12:46 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
